Improved wallet funding
IntaSend/intasend-php pull request #9
Opened 2023-09-19 14:18 UTC by mugendi-gitonga

2023-09-19 14:23 UTC, felixcheruiyot requested changes

2023-09-19 14:23 UTC, felixcheruiyot commented on src/Wallet.php
> +        return $collection->create($amount=$amount, $phone_number=$phone_number, $currency="KES", $method="MPESA_STK_PUSH", $api_ref="API Request", $name=null, $email=null, $wallet_id=$wallet_id);
$api_ref=$api_ref

2023-09-19 14:38 UTC, mugendi-gitonga commented on src/Wallet.php
> +        return $collection->create($amount=$amount, $phone_number=$phone_number, $currency="KES", $method="MPESA_STK_PUSH", $api_ref="API Request", $name=null, $email=null, $wallet_id=$wallet_id);
Implemented the changes

2023-09-20 08:41 UTC, felixcheruiyot approved these changes

2023-09-20 08:46 UTC, merged